name: 'Samueljklee blog using fastpages.'
description: Samuel's blog using fastpages. All credits to Hamel Husain and team.
author: Samuel Lee
inputs:
  BOOL_SAVE_MARKDOWN:
    description: Either 'true' or 'false'.  Whether or not to commit converted markdown files from notebooks and word documents into the _posts directory in your repo.  This is useful for debugging.
    required: false
    default: false
  SSH_DEPLOY_KEY:
    description: a ssh deploy key is required if BOOL_SAVE_MARKDOWN = 'true'
    required: false
branding:
  color: 'blue'
  icon: 'book'
runs:
  using: 'docker'
  image: 'Dockerfile'
